# Generated by Django 5.0.4 on 2024-04-15 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overhead_cost', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='PriceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=500)),
                ('invoice_id', models.CharField(max_length=50)),
                ('invoice_title', models.CharField(max_length=255)),
                ('company_location', models.CharField(max_length=255)),
                ('moodboard_price', models.CharField(blank=True, default='FREE', max_length=100, null=True)),
                ('illustration_price', models.CharField(blank=True, default='FREE', max_length=100, null=True)),
                ('storyboard_price', models.CharField(blank=True, default='FREE', max_length=100, null=True)),
                ('compositing_price', models.CharField(blank=True, default='FREE', max_length=100, null=True)),
                ('editing_price', models.CharField(blank=True, default='FREE', max_length=100, null=True)),
                ('motion_price', models.CharField(blank=True, default='FREE', max_length=100, null=True)),
                ('modelling_price', models.CharField(blank=True, default='FREE', max_length=100, null=True)),
                ('texturing_price', models.CharField(blank=True, default='FREE', max_length=100, null=True)),
                ('rigging_price', models.CharField(blank=True, default='FREE', max_length=100, null=True)),
                ('lookdev_price', models.CharField(blank=True, default='FREE', max_length=100, null=True)),
                ('layout_price', models.CharField(blank=True, default='FREE', max_length=100, null=True)),
                ('animation_price', models.CharField(blank=True, default='FREE', max_length=100, null=True)),
                ('fx_price', models.CharField(blank=True, default='FREE', max_length=100, null=True)),
                ('lighting_price', models.CharField(blank=True, default='FREE', max_length=100, null=True)),
                ('rendering_price', models.CharField(blank=True, default='FREE', max_length=100, null=True)),
                ('voiceover_price', models.CharField(blank=True, default='FREE', max_length=100, null=True)),
                ('audio_studio_price', models.CharField(blank=True, default='FREE', max_length=100, null=True)),
                ('music_sync_price', models.CharField(blank=True, default='FREE', max_length=100, null=True)),
                ('prod_mgt', models.CharField(blank=True, default='FREE', max_length=100, null=True)),
                ('total_sum', models.CharField(blank=True, default='FREE', max_length=100, null=True)),
                ('vat_price', models.CharField(blank=True, default='FREE', max_length=100, null=True)),
                ('final_cost', models.CharField(blank=True, default='FREE', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, default=None, max_digits=15)),
                ('task', models.CharField(default=None, max_length=50)),
            ],
            options={
                'verbose_name': 'Salary',
                'verbose_name_plural': 'Salaries',
            },
        ),
        migrations.CreateModel(
            name='PriceInclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodboard', models.BooleanField(default=True)),
                ('illustration', models.BooleanField(default=True)),
                ('storyboard', models.BooleanField(default=True)),
                ('compositing', models.BooleanField(default=True)),
                ('editing', models.BooleanField(default=True)),
                ('motion', models.BooleanField(default=True)),
                ('modelling', models.BooleanField(default=True)),
                ('texturing', models.BooleanField(default=True)),
                ('rigging', models.BooleanField(default=True)),
                ('animation', models.BooleanField(default=True)),
                ('fx', models.BooleanField(default=True)),
                ('lighting', models.BooleanField(default=True)),
                ('rendering', models.BooleanField(default=True)),
                ('voiceover', models.BooleanField(default=True)),
                ('music_sync', models.BooleanField(default=True)),
                ('audio_studio', models.BooleanField(default=True)),
                ('layout', models.BooleanField(default=True)),
                ('lookdev', models.BooleanField(default=True)),
                ('price_detail', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.pricedetail')),
            ],
        ),
    ]
