# Generated by Django 5.0.1 on 2024-02-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salaries',
            options={'verbose_name': 'Salary', 'verbose_name_plural': 'Salaries'},
        ),
        migrations.RemoveField(
            model_name='cost',
            name='total_salary',
        ),
        migrations.RemoveField(
            model_name='salaries',
            name='salary',
        ),
        migrations.AddField(
            model_name='salaries',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=15),
        ),
    ]
