# Generated by Django 5.0.1 on 2024-02-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_salaries_options_remove_cost_total_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('invoice_id', models.CharField(max_length=50)),
                ('moodboard_days', models.IntegerField()),
                ('moodboard_artists', models.IntegerField()),
                ('illustration_days', models.IntegerField()),
                ('illustration_artists', models.IntegerField()),
                ('storyboard_days', models.IntegerField()),
                ('storyboard_artists', models.IntegerField()),
                ('compositing_artists', models.IntegerField()),
                ('compositing_days', models.IntegerField()),
                ('editing_days', models.IntegerField()),
                ('editing_artists', models.IntegerField()),
                ('motion_days', models.IntegerField()),
                ('motion_artists', models.IntegerField()),
                ('modelling_days', models.IntegerField()),
                ('texturing_days', models.IntegerField()),
                ('rigging_days', models.IntegerField()),
                ('lookdev_days', models.IntegerField()),
                ('layout_days', models.IntegerField()),
                ('animation_days', models.IntegerField()),
                ('fx_days', models.IntegerField()),
                ('lighting_days', models.IntegerField()),
                ('rendering_days', models.IntegerField()),
                ('modelling_artists', models.IntegerField()),
                ('texturing_artists', models.IntegerField()),
                ('rigging_artists', models.IntegerField()),
                ('lookdev_artists', models.IntegerField()),
                ('layout_artists', models.IntegerField()),
                ('animation_artists', models.IntegerField()),
                ('fx_artists', models.IntegerField()),
                ('lighting_artists', models.IntegerField()),
                ('rendering_artists', models.IntegerField()),
                ('voiceover_salary', models.IntegerField()),
                ('audio_studio_days', models.IntegerField()),
                ('audio_studio_artists', models.IntegerField()),
                ('music_sync_days', models.IntegerField()),
                ('music_sync_artists', models.IntegerField()),
            ],
        ),
    ]
