# Generated by Django 5.0.1 on 2024-02-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_pricedetail_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricedetail',
            name='animation_price',
            field=models.CharField(default='FREE', max_length=100),
        ),
        migrations.AddField(
            model_name='pricedetail',
            name='audio_studio_price',
            field=models.CharField(default='FREE', max_length=100),
        ),
        migrations.AddField(
            model_name='pricedetail',
            name='compositing_price',
            field=models.CharField(default='FREE', max_length=100),
        ),
        migrations.AddField(
            model_name='pricedetail',
            name='editing_price',
            field=models.CharField(default='FREE', max_length=100),
        ),
        migrations.AddField(
            model_name='pricedetail',
            name='fx_price',
            field=models.CharField(default='FREE', max_length=100),
        ),
        migrations.AddField(
            model_name='pricedetail',
            name='illustration_price',
            field=models.CharField(default='FREE', max_length=100),
        ),
        migrations.AddField(
            model_name='pricedetail',
            name='layout_price',
            field=models.CharField(default='FREE', max_length=100),
        ),
        migrations.AddField(
            model_name='pricedetail',
            name='lighting_price',
            field=models.CharField(default='FREE', max_length=100),
        ),
        migrations.AddField(
            model_name='pricedetail',
            name='lookdev_price',
            field=models.CharField(default='FREE', max_length=100),
        ),
        migrations.AddField(
            model_name='pricedetail',
            name='modelling_price',
            field=models.CharField(default='FREE', max_length=100),
        ),
        migrations.AddField(
            model_name='pricedetail',
            name='moodboard_price',
            field=models.CharField(default='FREE', max_length=100),
        ),
        migrations.AddField(
            model_name='pricedetail',
            name='motion_price',
            field=models.CharField(default='FREE', max_length=100),
        ),
        migrations.AddField(
            model_name='pricedetail',
            name='music_sync_price',
            field=models.CharField(default='FREE', max_length=100),
        ),
        migrations.AddField(
            model_name='pricedetail',
            name='rendering_price',
            field=models.CharField(default='FREE', max_length=100),
        ),
        migrations.AddField(
            model_name='pricedetail',
            name='rigging_price',
            field=models.CharField(default='FREE', max_length=100),
        ),
        migrations.AddField(
            model_name='pricedetail',
            name='storyboard_price',
            field=models.CharField(default='FREE', max_length=100),
        ),
        migrations.AddField(
            model_name='pricedetail',
            name='texturing_price',
            field=models.CharField(default='FREE', max_length=100),
        ),
        migrations.AlterField(
            model_name='pricedetail',
            name='voiceover_salary',
            field=models.IntegerField(default=0),
        ),
    ]
