# Generated by Django 5.0.3 on 2024-03-26 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_pricedetail_voiceover_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceInclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodboard', models.BooleanField(default=False)),
                ('illustration', models.BooleanField(default=False)),
                ('storyboard', models.BooleanField(default=False)),
                ('compositing', models.BooleanField(default=False)),
                ('editing', models.BooleanField(default=False)),
                ('motion', models.BooleanField(default=False)),
                ('modelling', models.BooleanField(default=False)),
                ('texturing', models.BooleanField(default=False)),
                ('rigging', models.BooleanField(default=False)),
                ('animation', models.BooleanField(default=False)),
                ('fx', models.BooleanField(default=False)),
                ('lighting', models.BooleanField(default=False)),
                ('rendering', models.BooleanField(default=False)),
                ('voiceover', models.BooleanField(default=False)),
                ('music_sync', models.BooleanField(default=False)),
                ('audio_studio', models.BooleanField(default=False)),
                ('layout', models.BooleanField(default=False)),
                ('lookdev', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='pricedetail',
            name='price_include',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.priceinclude'),
        ),
    ]
