# Generated by Django 5.0.3 on 2024-03-26 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_priceinclude_pricedetail_price_include'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricedetail',
            name='price_include',
        ),
        migrations.AddField(
            model_name='priceinclude',
            name='price_detail',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.pricedetail'),
        ),
    ]
