# Generated by Django 5.0.3 on 2024-03-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_pricedetail_price_include_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricedetail',
            name='project_title',
            field=models.CharField(choices=[('3D Animation', '3D Animation'), ('Visual Effects', 'Visual Effects')], default='3D Animation', max_length=255),
        ),
        migrations.AlterField(
            model_name='priceinclude',
            name='animation',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='priceinclude',
            name='audio_studio',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='priceinclude',
            name='compositing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='priceinclude',
            name='editing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='priceinclude',
            name='fx',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='priceinclude',
            name='illustration',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='priceinclude',
            name='layout',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='priceinclude',
            name='lighting',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='priceinclude',
            name='lookdev',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='priceinclude',
            name='modelling',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='priceinclude',
            name='moodboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='priceinclude',
            name='motion',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='priceinclude',
            name='music_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='priceinclude',
            name='rendering',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='priceinclude',
            name='rigging',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='priceinclude',
            name='storyboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='priceinclude',
            name='texturing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='priceinclude',
            name='voiceover',
            field=models.BooleanField(default=True),
        ),
    ]
