# Generated by Django 5.0.3 on 2024-04-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_pricedetail_project_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricedetail',
            name='project_title',
        ),
    ]
