# Generated by Django 5.0.3 on 2024-04-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_pricedetail_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricedetail',
            name='company_location',
            field=models.CharField(default='Lagos', max_length=255),
        ),
        migrations.AddField(
            model_name='pricedetail',
            name='invoice_title',
            field=models.CharField(default='Normal', max_length=50),
        ),
    ]
